language: python
python:
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO="~=1.11"
  - DJANGO="~=2.2"
  - DJANGO="~=3.0"
before_install:
  - export DJANGO_SETTINGS_MODULE=jet.tests.settings
install:
  - pip install -q "Django${DJANGO}"
  - pip install .
  - pip install coverage==5.0.3
  - pip install coveralls==1.10.0
script:
  - coverage run --source=jet --omit=*/migrations/*,*/tests/* manage.py test jet
after_success:
  - coverage report
  - coveralls
